=== hayley-d/IMY-210/practical-3/data/notes_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--Hayley Dodkins u21528790-->
    <xs:element name="notes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="note" type="noteType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="noteType">
        <xs:sequence>
            <xs:element name="author" type="xs:string"/>
            <xs:element name="content" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== hayley-d/IMY-210/practical-3/data/notes.xml
<?xml version="1.0" encoding="UTF-8"?>
<notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./notes_schema.xsd">
    <!--Hayley Dodkins u21528790-->
    <note id="1">
        <author>Tom Nook</author>
        <content>You're island needs some work.</content>
    </note>
    <note id="2">
        <author>Test Subject 234</author>
        <content>The cake is a lie.</content>
    </note>
    <note id="3">
        <author>Mooncake</author>
        <content>Chookity Dookity.</content>
    </note>
</notes>
