=== hayley-d/IMY-210/project/phase-2/xmlFiles/userValidate.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--Hayley Dodkins u21528790-->

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <!--Define the node element-->
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="username" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="role" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="storeId" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hayley-d/IMY-210/project/phase-2/xmlFiles/users.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="userValidate.xsd">
  <user>
    <id>43</id>
    <username>john_doe</username>
    <password>password123</password>
    <role>store_owner</role>
  </user>
  <user>
    <id>2</id>
    <username>jane_smith</username>
    <password>password456</password>
    <role>store_owner</role>
  </user>
  <user>
    <id>53</id>
    <username>Mooncake</username>
    <password>123</password>
    <role>customer</role>
  </user>
</users>
