=== hayley-d/IMY-210/project/validate.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--Hayley Dodkins u21528790-->
    <!--Define element for a store-->
    <xs:element name="store">
        <xs:complexType>
            <xs:sequence>
                <!--Define the info element for the store details-->
                <xs:element name="information" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="owner">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="userId" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                <!--Define product element-->
                <xs:element name="products">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="product" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="author" type="xs:string"/>
                                        <xs:element name="isbn" type="xs:string"/>
                                        <xs:element name="sku" type="xs:string"/>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="price">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="currency" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="department" type="xs:string"/>
                                        <!--Define modules element-->
                                        <xs:element name="modules">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="module" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="id" type="xs:string" use="required"/>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="availability" type="xs:string"/>
                                        <xs:element name="condition" type="xs:string"/>
                                        <xs:element name="image" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="language" type="xs:string" use="required"/>
                                    <xs:attribute name="edition" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hayley-d/IMY-210/project/phase-2/xmlFiles/43.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validate.xsd">
  <information id="1">
    <name>Nintendo Novel Nook</name>
    <description> Immerse yourself in the fantastical worlds of gaming and storytelling at Nintendo Novel Nook. Uncover hidden gems and classic favorites inspired by beloved video game franchises. Whether you're a Mario aficionado, a Zelda enthusiast, or a Pokémon trainer, embark on epic literary adventures that capture the magic of Nintendo.</description>
    <owner userId="43">John Doe</owner>
  </information>
  <products>
    <product id="NINTENDO1" language="En" edition="1st">
      <title>Super Mario Encyclopedia</title>
      <author>Nintendo</author>
      <isbn>10: 0-13-822139-1</isbn>
      <sku>13: 978-0-13-822139-3</sku>
      <description> Super Mario Bros. Encyclopedia: The Official Guide to the First 30 Years is jam-packed with content from all seventeen Super Mario games</description>
      <price currency="USD">21</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Brand New</condition>
      <image>sample.jpg</image>
    </product>

    <product id="NINTENDO2" language="En" edition="1st">
      <title>The Essential Handbook for Nintendo Switch</title>
      <author>Mortimer Children's Books</author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>It's filled with everything a Switch owner needs to know</description>
      <price currency="USD">9.95</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Great</condition>
      <image>NINTENDO.png</image>
    </product>

    <product id="NINTENDO3" language="En" edition="Deluxe">
      <title>The Legend of Zelda Encyclopedia</title>
      <author>Nintendo</author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>The Legend of Zelda is one of the most successful franchises of all time with nearly twenty video games and thirty years of history, but it all started with a gold cartridge...</description>
      <price currency="USD">46</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>Out of Stock</availability>
      <condition>New</condition>
      <image>NINTENDO.png</image>
    </product>

    <product id="NINTENDO4" language="En" edition="Unabridged">
      <title>Disrupting the Game: From the Bronx to the Top of Nintendo</title>
      <author>Reggie Fils-Aimé </author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>WALL STREET JOURNAL BESTSELLER</description>
      <price currency="USD">14.95</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>Out of Stock</availability>
      <condition>Great</condition>
      <image>NINTENDO.png</image>
    </product>

    <product id="NINTENDO5" language="En" edition="1st">
      <title>Console Wars: Sega Vs Nintendo</title>
      <author>Blake Harris</author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>In 1990 Nintendo had a virtual monopoly on the video game industry. Sega, on the other hand, was a faltering arcade company with big aspirations and even bigger personalities. </description>
      <price currency="USD">11.94</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>NINTENDO.png</image>
    </product>

    <product id="NINTENDO6" language="En" edition="1st">
      <title>The NES Encyclopedia</title>
      <author>Chris Scullion</author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>The NES is one of the most iconic video game systems of all time, and is credited with ‘saving’ the American video games industry in the early 80s when it looked likely to collapse.</description>
      <price currency="USD">34</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>New</condition>
      <image>NINTENDO.png</image>
    </product>

    <product id="NINTENDO7" language="En" edition="1st">
      <title>The Art of Super Mario Odyssey</title>
      <author>Cathy Ballou Mealey</author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>A book about Mario</description>
      <price currency="USD">13</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>NINTENDO.png</image>
    </product>

    <product id="NINTENDO8" language="En" edition="1st">
      <title>The Big Book of Nintendo</title>
      <author>Future Publishing Ltd</author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>Explore Nintendo's journey from an obscure Kyoto-based company to global videogaming powerhouse through some of their most iconic games and consoles.</description>
      <price currency="USD">21</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>Out of Stock</availability>
      <condition>Fine</condition>
      <image>NINTENDO.png</image>
    </product>

    <product id="NINTENDO9" language="En" edition="1st">
      <title>The N64 Encyclopedia</title>
      <author>Chris Scullion </author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>The fourth book in Chris Scullion’s critically acclaimed series of video game encyclopedias, The N64 Encyclopedia is dedicated to the Nintendo 64, one of the most well-loved games consoles ever released. </description>
      <price currency="USD">30</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Great</condition>
      <image>NINTENDO.png</image>
    </product>

    <product id="NINTENDO10" language="En" edition="1st">
      <title>Seeing Red: Nintendo's Virtual Boy</title>
      <author>Jose P. Zagal</author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>The curious history, technology, and technocultural context of Nintendo’s short-lived stereoscopic gaming console, the Virtual Boy.</description>
      <price currency="USD">30</price>
      <department>NINTENDO</department>
      <modules>
        <module id="NINTENDO" name="NINTENDO 101"/>
      </modules>
      <availability>Out of Stock</availability>
      <condition>Used</condition>
      <image>NINTENDO.png</image>
    </product>
  </products>
</store>

=== hayley-d/IMY-210/project/phase-2/xmlFiles/271940.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validate.xsd">
  <information id="271940">
    <name>Slothful Pages</name>
    <description>We only sell sloth related books.</description>
    <owner userId="271940">&#xD;
            SlothySavant&#xD;
        </owner>
  </information>
  <products>
    <product id="BAlE1" language="En" edition="70th">
      <title>Sloths in the Amazon</title>
      <author>Hayley Dodkins</author>
      <isbn>123123-2131-223</isbn>
      <sku>123123-2131-223</sku>
      <description>About sloths living in the amazon</description>
      <price currency="USD">1500</price>
      <department>Sloth</department>
      <modules>
        <module id="COS" name="COS"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Great</condition>
      <image>Sloth.png</image>
    </product>

    <product id="BAlC2" language="En" edition="1st">
      <title>Life in the Sloth Lane: Slow Down and Smell the Hibiscus</title>
      <author>Lucy Cooke</author>
      <isbn>978-0761193227</isbn>
      <sku>0761193227</sku>
      <description>Perhaps it’s because they’ve mastered the art of taking it slow in a world whose frenzied pace is driving the rest of us crazy. Here, in a mindfulness book like no other, heart-tuggingly cute photographs of these always-chill creatures are paired with words of wisdom, all to inspire us to slow down, stop to enjoy the little things, and come up relaxed, centered, and smiling.</description>
      <price currency="USD">188</price>
      <department>SLO</department>
      <modules>
        <module id="SLO101" name="Sloths 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>Sloth.png</image>
    </product>

    <product id="BAlX3" language="En" edition="1st">
      <title>Mindful Mr. Sloth</title>
      <author>Katy Hudson</author>
      <isbn>978-1684467952</isbn>
      <sku>1684467950</sku>
      <description>Mr. Sloth has one speed--slow. He loves to do things one at a time, at a nice, easy pace. Can Mr. Sloth's mindful ways teach Sasha to slow down and enjoy life?</description>
      <price currency="USD">120</price>
      <department>SLO</department>
      <modules>
        <module id="SLO102" name="Sloths 102"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>Sloth.png</image>
    </product>

    <product id="BAlZ4" language="En" edition="1st">
      <title>"Slowly, Slowly, Slowly," said the Sloth</title>
      <author>Eric Carle</author>
      <isbn>978-0142408476</isbn>
      <sku>0142408476</sku>
      <description>Slowly, slowly, slowly . . . that's the way the sloth moves. Slowly, it eats and then, slowly, it falls asleep. "What strange kind of creature is this?" the other animals wonder.</description>
      <price currency="ZAR">257</price>
      <department>SLO</department>
      <modules>
        <module id="SLO103" name="Sloths 103"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>Sloth.png</image>
    </product>

    <product id="BAlA5" language="En" edition="3rd">
      <title>Where's the Sloth?: A Super Sloth Search Book</title>
      <author>Andy Rowland</author>
      <isbn>978-1454934035</isbn>
      <sku>1454934034</sku>
      <description>Ever since Suzi sloth began to wonder about the world beyond her rainforest home, she’s longed for adventure. So she gathered her friends and they’re all going on a globetrotting tour of amazing cities.</description>
      <price currency="ZAR">163</price>
      <department>SLO</department>
      <modules>
        <module id="SLO103" name="Sloths 103"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>Sloth.png</image>
    </product>

    <product id="BAlS6" language="En" edition="2nd">
      <title>Bedtime for Baby Sloth</title>
      <author>Danielle McLean </author>
      <isbn>978-1680106008</isbn>
      <sku>1680106007</sku>
      <description>High up in the treetops, Mommy Sloth calls to her baby, “Come down, little one. It’s time for bed.” But Baby Sloth isn’t ready for bed. First she needs to say good night to the moon. And then she needs to sing a song to the birds. And what about a bedtime snack? Will Baby Sloth EVER be ready for bed?</description>
      <price currency="ZAR">171</price>
      <department>SLO</department>
      <modules>
        <module id="SLO103" name="Sloths 103"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>Sloth.png</image>
    </product>

    <product id="BAlA7" language="En" edition="3rd">
      <title>What is a Sloth?</title>
      <author>Ginger Swift</author>
      <isbn>978-1680526332</isbn>
      <sku>1680526332</sku>
      <description>Surprise and delight with bright artwork and fun sloth facts found under every flap</description>
      <price currency="USD">6</price>
      <department>SLO</department>
      <modules>
        <module id="SLO101" name="Sloths 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>Sloth.png</image>
    </product>

    <product id="BAlA8" language="En" edition="1st">
      <title>I Love You Slow Much</title>
      <author>Rose Rossner</author>
      <isbn>978-1728260075</isbn>
      <sku>1728260078</sku>
      <description>There's nothing better than hanging together with someone you love slow much! Combining gorgeous illustrations, charming animal puns, and an evergreen message of love and encouragement, this wildly sweet book is a pun-derful way show your llamazing little one you'll always be there.</description>
      <price currency="USD">9</price>
      <department>SLO</department>
      <modules>
        <module id="SLO101" name="Sloths 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>Sloth.png</image>
    </product>

    <product id="BAlA9" language="En" edition="3rd">
      <title>The Little Book of Sloth Philosophy</title>
      <author>Jennifer McCartney</author>
      <isbn>978-0008313692</isbn>
      <sku>0008313695</sku>
      <description>Relax, unwind and soak up the wisdom of the sloth with the slowest page turner you’ll ever read.</description>
      <price currency="USD">8</price>
      <department>SLO</department>
      <modules>
        <module id="SLO101" name="Sloths 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>Sloth.png</image>
    </product>

    <product id="BAlA10" language="En" edition="3rd">
      <title>Sloth and Squirrel in a Pickle</title>
      <author>Cathy Ballou Mealey</author>
      <isbn>978-1525302381</isbn>
      <sku>1525302388</sku>
      <description>A speedy squirrel and a sleepy sloth try to get the job done in this funny, heartwarming tale of two lovable, but unlikely, friends.</description>
      <price currency="USD">13</price>
      <department>SLO</department>
      <modules>
        <module id="SLO101" name="Sloths 101"/>
      </modules>
      <availability>In Stock</availability>
      <condition>Good</condition>
      <image>Sloth.png</image>
    </product>
  </products>
</store>

=== hayley-d/IMY-210/project/phase-2/xmlFiles/22.xml
<?xml version="1.0" encoding="UTF-8"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validate.xsd">
    <information id="4">
        <name>
            Wize Books
        </name>
        <description>
            desc
        </description>
        <owner userId="22">
            Tom Nook
        </owner>
    </information>
    <products>
        <product id="tom-nook-textbook-1" language="en" edition="12">
            <title>
                Introduction to economy
            </title>
            <author>
                Tom Nook
            </author>
            <isbn>
                978-0-13-518276-3
            </isbn>
            <sku>
                ECON-INTRO-2
            </sku>
            <description>
                Introduction to economics introduces you to economics
            </description>
            <price currency="ZAR">
                250.00
            </price>
            <department>
                Economics
            </department>
            <modules>
                <module id="ecn210" name="ECN 210"/>
            </modules>
            <availability>
                in stock
            </availability>
            <condition>
                great
            </condition>
            <image>
                ./images/xml-books1.png
            </image>
        </product>
    </products>
</store>
