=== hayley-d/IMY-210/project/validate.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--Hayley Dodkins u21528790-->
    <!--Define element for a store-->
    <xs:element name="store">
        <xs:complexType>
            <xs:sequence>
                <!--Define the info element for the store details-->
                <xs:element name="information" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="owner">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="userId" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                <!--Define product element-->
                <xs:element name="products">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="product" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="author" type="xs:string"/>
                                        <xs:element name="isbn" type="xs:string"/>
                                        <xs:element name="sku" type="xs:string"/>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="price">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="currency" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="department" type="xs:string"/>
                                        <!--Define modules element-->
                                        <xs:element name="modules">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="module" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="id" type="xs:string" use="required"/>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="availability" type="xs:string"/>
                                        <xs:element name="condition" type="xs:string"/>
                                        <xs:element name="image" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="language" type="xs:string" use="required"/>
                                    <xs:attribute name="edition" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hayley-d/IMY-210/project/phase-2/xmlFiles/864560.xml
<?xml version="1.0" encoding="UTF-8"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validate.xsd">
    <information id="864560">
        <name>
            Cisco Library Emporium
        </name>
        <description>
            Step into the world of networking and technology at Cisco Library Emporium. Discover a treasure trove of resources on networking, cybersecurity, and IT infrastructure. From beginner guides to advanced manuals, our curated selection of books offers something for everyone interested in mastering Cisco technologies.
        </description>
        <owner userId="864560">
            CiscoPress
        </owner>
    </information>
    <products>
        <product id="CIS1" language="En" edition="3rd">
            <title>CCNA 200-301 Official Cert Guide Library</title>
            <author>Wendell Odom, David Hucaby, Jason Gooley</author>
            <isbn>10: 0-13-822139-1</isbn>
            <sku>13: 978-0-13-822139-3</sku>
            <description>Cisco Press has the only study guides approved by Cisco for the new CCNA certification. The new edition of the best-selling two-book value-priced CCNA 200-301 Official Cert Guide Library, Second Edition presents you with an organized test-preparation routine using proven series elements and techniques. </description>
            <price currency="USD">95.5</price>
            <department>COS</department>
            <modules>
                <module id="SLO101" name="Sloths 101"/>
            </modules>
            <availability>In Stock</availability>
            <condition>Brand New</condition>
            <image>sample.jpg</image>
        </product>

        <product id="CIS2" language="En" edition="Unabridged">
            <title>Kali Linux for Beginners</title>
            <author>Jowanna Lewis</author>
            <isbn>978-1525302381</isbn>
            <sku>1525302388</sku>
            <description>Most of the big companies today seek the help of Kali Linux for the purpose of tracing and checking the various forms of vulnerabilities which are present within a system and thus ensures 100 percent security for an organization. Unless and until you are unaware of the basics, you will not be able to use this software.</description>
            <price currency="USD">16</price>
            <department>KALI</department>
            <modules>
                <module id="KALI101" name="KALI 101"/>
            </modules>
            <availability>In Stock</availability>
            <condition>New</condition>
            <image>kali.png</image>
        </product>

        <product id="CIS3" language="En" edition="3rd">
            <title>Cisco Certified DevNet Associate DEVASC 200-901</title>
            <author>Chris Jackson</author>
            <isbn>978-1525302381</isbn>
            <sku>1525302388</sku>
            <description>Cisco Certified DevNet Associate DEVASC 200-901 Official Cert Guide presents you with an organized test preparation routine using proven series elements and techniques.</description>
            <price currency="USD">50</price>
            <department>CISCO</department>
            <modules>
                <module id="CISCO200" name="CISCO 200"/>
            </modules>
            <availability>Out of Stock</availability>
            <condition>Used</condition>
            <image>cisco.png</image>
        </product>

        <product id="CIS4" language="En" edition="3rd">
            <title>CCNP Enterprise Wireless Design ENWLSD 300-425</title>
            <author>Jerome Henry</author>
            <isbn>978-1525302381</isbn>
            <sku>1525302388</sku>
            <description>Trust the best-selling Official Cert Guide series from Cisco Press to help you learn, prepare, and practice for the CCNP Enterprise Wireless ENWLSD 300-425 and ENWLSI 300-430 exams.</description>
            <price currency="USD">75</price>
            <department>SICO</department>
            <modules>
                <module id="SICO 300" name="SICO 300"/>
            </modules>
            <availability>In Stock</availability>
            <condition>Great</condition>
            <image>ciso.png</image>
        </product>

        <product id="CIS5" language="En" edition="3rd">
            <title>Cisco Certified Support Technician (CCST) Networking 100-150</title>
            <author>Allan Johnson</author>
            <isbn>978-1525302381</isbn>
            <sku>1525302388</sku>
            <description> most practical way to understand the Cisco Certified Support Technician (CCST) Networking certification process, to commit to taking your CCST Networking 200-301 exam, and to finish your preparation using a variety of primary and supplemental study resources.</description>
            <price currency="USD">39</price>
            <department>CISO</department>
            <modules>
                <module id="CISO304" name="CISO 304"/>
            </modules>
            <availability>Out of Stock</availability>
            <condition>Great</condition>
            <image>ciso.png</image>
        </product>

        <product id="CIS6" language="En" edition="3rd">
            <title>CCNP and CCIE Security Core SCOR 350-701 Official Cert Guide</title>
            <author>Omar Santos </author>
            <isbn>978-1525302381</isbn>
            <sku>1525302388</sku>
            <description>Trust the best-selling Official Cert Guide series from Cisco Press to help you learn, prepare, and practice for the CCNP and CCIE Security Core SCOR 350-701 exam. </description>
            <price currency="USD">69</price>
            <department>DEV</department>
            <modules>
                <module id="DEV402" name="DEV402"/>
            </modules>
            <availability>In Stock</availability>
            <condition>Good</condition>
            <image>dev.png</image>
        </product>

        <product id="CIS7" language="En" edition="1st">
            <title>Cisco Certified Support Technician (CCST) Cybersecurity 100-160 Official Cert Guide</title>
            <author>Shane Sexton</author>
            <isbn>978-1525302381</isbn>
            <sku>1525302388</sku>
            <description>Trust the best-selling Official Cert Guide series from Cisco Press to help you learn, prepare, and practice for the CCST Cybersecurity 100-160 exam. </description>
            <price currency="USD">32</price>
            <department>DEV</department>
            <modules>
                <module id="DEV501" name="DEV501"/>
            </modules>
            <availability>In Stock</availability>
            <condition>Great</condition>
            <image>cis.png</image>
        </product>

        <product id="CIS8" language="En" edition="2nd">
            <title>CCNP Enterprise Core ENCOR 350-401 and Advanced Routing ENARSI 300-410 Official Cert Guide Library</title>
            <author>Brad Edgeworth</author>
            <isbn>978-1525302381</isbn>
            <sku>1525302388</sku>
            <description>isco Press has the only Study Guides approved by Cisco for the new CCNP Enterprise Certification.</description>
            <price currency="USD">119</price>
            <department>CIS</department>
            <modules>
                <module id="CIS901" name="CIS901"/>
            </modules>
            <availability>Out of Stock</availability>
            <condition>Great</condition>
            <image>sic.png</image>
        </product>

        <product id="CIS9" language="En" edition="2nd">
            <title>CCNP Enterprise Advanced Routing ENARSI 300-410 Official Cert Guide</title>
            <author>Brad Edgeworth</author>
            <isbn>978-1525302381</isbn>
            <sku>1525302388</sku>
            <description>Trust the best-selling Official Cert Guide series from Cisco Press to help you learn, prepare, and practice for the 300-410 ENARSI exam.</description>
            <price currency="USD">74</price>
            <department>DEV</department>
            <modules>
                <module id="DEV102" name="DEV102"/>
            </modules>
            <availability>In Stock</availability>
            <condition>Great</condition>
            <image>cisc.png</image>
        </product>

        <product id="CIS10" language="En" edition="1st">
            <title>Cisco Certified DevNet Professional DEVCOR 350-901 Official Cert Guide </title>
            <author>Hazim Dahir</author>
            <isbn>978-1525302381</isbn>
            <sku>1525302388</sku>
            <description>Cisco Certified DevNet Professional DEVCOR 350-901 Official Cert Guide presents you with an organized test preparation routine using proven series elements and techniques</description>
            <price currency="USD">64</price>
            <department>OPS</department>
            <modules>
                <module id="OPS204" name="OPS204"/>
            </modules>
            <availability>Out of Stock</availability>
            <condition>Great</condition>
            <image>ops.png</image>
        </product>
    </products>
</store>

=== hayley-d/IMY-210/project/phase-2/xmlFiles/959149.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validate.xsd">
  <information id="959149">
    <name>&#xD;
        DevOps Book Haven&#xD;
        </name>
    <description>&#xD;
        Welcome to DevOps Book Haven, your go-to destination for all things related to development and operations. Explore our vast collection of books covering software development, automation, cloud computing, and more. Whether you're a seasoned engineer or a curious beginner, find the resources you need to thrive in the world of DevOps.&#xD;
        </description>
    <owner userId="959149">&#xD;
            hayley&#xD;
        </owner>
  </information>
  <products >
      <product id="DEV1" language="En" edition="1st">
          <title>The DevOps Handbook</title>
          <author>Gene Kim</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description> The DevOps Handbook has been the definitive guide for taking the successes laid out in the best-selling The Phoenix Project and applying them in any organization. Now, with this fully updated and expanded edition, itâ€™s time to take DevOps out of the IT department and apply it across the full business.</description>
          <price currency="USD">15</price>
          <department>DEV</department>
          <modules>
              <module id="DEV103" name="DevOps 103"/>
          </modules>
          <availability>In Stock</availability>
          <condition>Good</condition>
          <image>Dev.png</image>
      </product>

      <product id="DEV2" language="En" edition="2nd">
          <title>Learning DevOps</title>
          <author>Mikael Krief</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description>Implement modern DevOps techniques to increase business productivity, agility, reliability, security, and scalability</description>
          <price currency="USD">49</price>
          <department>Dev</department>
          <modules>
              <module id="Dev202" name="DevOps 202"/>
          </modules>
          <availability>In Stock</availability>
          <condition>Used</condition>
          <image>Devops.png</image>
      </product>

      <product id="DEV3" language="En" edition="3rd">
          <title>DevOps for the Desperate</title>
          <author>Bradley Smith</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description>DevOps for the Desperate is a hands-on, no-nonsense guide for those who land in a DevOps environment and need to get up and running quickly.</description>
          <price currency="USD">22</price>
          <department>Dev</department>
          <modules>
              <module id="DEV304" name="DEV304"/>
          </modules>
          <availability>In Stock</availability>
          <condition>Good</condition>
          <image>devoops.png</image>
      </product>

      <product id="DEV4" language="En" edition="2nd">
          <title>Cloud Native DevOps with Kubernetes</title>
          <author>Justin Domingus</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description>Kubernetes has become the operating system of today's cloud native world, providing a reliable and scalable platform for running containerized workloads. In this friendly, pragmatic book, cloud experts Justin Domingus and John Arundel show you what Kubernetes can do-and what you can do with it.</description>
          <price currency="USD">48</price>
          <department>DEV</department>
          <modules>
              <module id="DEV607" name="DEV607"/>
          </modules>
          <availability>In Stock</availability>
          <condition>Great</condition>
          <image>Sloth.png</image>
      </product>

      <product id="DEV5" language="En" edition="1st">
          <title>The Phoenix Project</title>
          <author>Gene Kim</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description>The Phoenix Project continues to guide IT in the DevOps revolution. </description>
          <price currency="USD">15</price>
          <department>DEV</department>
          <modules>
              <module id="DEV301" name="DEV301"/>
          </modules>
          <availability>In Stock</availability>
          <condition>Good</condition>
          <image>devvv.png</image>
      </product>

      <product id="DEV6" language="En" edition="illustrated">
          <title>DevOps For Dummies</title>
          <author>Emily Freeman</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description>DevOps embraces a culture of unifying the creation and distribution of technology in a way that allows for faster release cycles and more resource-efficient product updating. DevOps For Dummies provides a guidebook for those on the development or operations side in need of a primer on this way of working.</description>
          <price currency="USD">19</price>
          <department>OPS</department>
          <modules>
              <module id="OPS303" name="OPS 303"/>
          </modules>
          <availability>In Stock</availability>
          <condition>Great</condition>
          <image>ops.png</image>
      </product>

      <product id="DEV7" language="En" edition="1st">
          <title>Automating DevOps with GitLab CI/CD Pipelines</title>
          <author>Christopher Cowell</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description>Use GitLab CI/CD pipelines for automating and deploying different steps of your software development lifecycle using best practices and troubleshooting methods.</description>
          <price currency="USD">33</price>
          <department>OPSS</department>
          <modules>
              <module id="OPS405" name="OPS405"/>
          </modules>
          <availability>In Stock</availability>
          <condition>New</condition>
          <image>ooops.png</image>
      </product>

      <product id="DEV8" language="En" edition="1st">
          <title>Effective DevOps: Building a Culture of Collaboration, Affinity, and Tooling at Scale </title>
          <author>Jennifer Davis</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description>Devops stresses iterative efforts to break down information silos, monitor relationships, and repair misunderstandings that arise between and within teams in your organization.</description>
          <price currency="USD">26</price>
          <department>OPS</department>
          <modules>
              <module id="OPS103" name="OPS103"/>
          </modules>
          <availability>In Stock</availability>
          <condition>New</condition>
          <image>dev.png</image>
      </product>

      <product id="DEV9" language="En" edition="Unabridged">
          <title>Team Topologies</title>
          <author>Matthew Skelton</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description>Effective software teams are essential for any organization to deliver value continuously and sustainably. But how do you build the best team organization for your specific goals, culture, and needs?</description>
          <price currency="USD">15</price>
          <department>OPS</department>
          <modules>
              <module id="OPS204" name="OPS204"/>
          </modules>
          <availability>In Stock</availability>
          <condition>Great</condition>
          <image>dev.png</image>
      </product>

      <product id="DEV10" language="En" edition="Unabridged">
          <title>Thinking in Systems: A Primer</title>
          <author>Donella H. Meadows</author>
          <isbn>978-1525302381</isbn>
          <sku>1525302388</sku>
          <description>Thinking in Systems is a concise and crucial book offering insight for problem-solving on scales ranging from the personal to the global.</description>
          <price currency="USD">15</price>
          <department>DEV</department>
          <modules>
              <module id="DEV101" name="DEV101"/>
          </modules>
          <availability>In Stock</availability>
          <condition>Good</condition>
          <image>devvvv.png</image>
      </product>
  </products>
</store>
