=== hayley-d/IMY-210/assignment-2/l.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="l_menu.com" xmlns:l="l_menu.com">

    <xs:complexType name="priceType">
        <xs:simpleContent>
            <xs:restriction base="xs:positiveInteger">
                <xs:maxInclusive value="999"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="priceTypeTwo">
        <xs:complexContent>
            <xs:extension base="l:priceType">
                <xs:attribute name="unit" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="euro"/>
                            <xs:enumeration value="dollar"/>
                            <xs:enumeration value="rand"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="name" >
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="50"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="price" type="l:priceTypeTwo" />

    <xs:element name="calories">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:maxInclusive value="999"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:complexType name="foodType">
        <xs:all >
            <xs:element ref="l:name" maxOccurs="1"/>
            <xs:element ref="l:price" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="l:calories" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute name="id" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Za-z]{2}\d{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:element name="food" type="l:foodType"/>

    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="l:food" maxOccurs="4" minOccurs="2"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== hayley-d/IMY-210/assignment-2/xsd-xml-2.xml
<?xml version="1.0"?>
<l:menu 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="l_menu.com l.xsd"
  xmlns:l="l_menu.com"> 
  <!-- <menu > can hold between 2 to 4 food items -->

  <l:food id="LM01"> 
    <!-- the attribute @id has to be 2 character followed by 2 digits -->
    <!-- the elements <price> and <calories> within <food> are both optional-->
    <!-- the elements in <food> has to follow the order <name> <price> <calories> -->

    <l:name>Salade César</l:name>
    <!-- the <name> element must be less than 50 characters-->

    <l:price unit="euro">90</l:price>
    <!-- the attirbute @unit can either be euro, dollar, or rand-->
    <!-- the <price> element must hold a positive integer no large than 999-->

    <l:calories>250</l:calories>
    <!-- the <calories> element must hold a positive integer no large than 999-->
  </l:food>

  <l:food id="LM02">
    <l:name>Sandwich au Poulet Grillé</l:name>
    <l:calories>450</l:calories>
  </l:food>

  <l:food id="LM03">
    <l:name>Pizza Margherita</l:name>
    <l:price unit="dollar">130</l:price>
  </l:food>

  <l:food id="LM04">
    <l:name>Burrito au Bœuf</l:name>
    <l:price unit="rand">100</l:price>
    <l:calories>520</l:calories>
  </l:food >
</l:menu>
